teams = [
    "Ducks",
    "Coyotes",
    "Bruins",
    "Sabres",
    "Flames",
    "Hurricanes",
    "Blackhawks",
    "Avalanche",
    "Blue Jackets",
    "Stars",
    "Red Wings",
    "Oilers",
    "Panthers",
    "Kings",
    "Wild",
    "Canadiens",
    "Predators",
    "Devils",
    "Islanders",
    "Rangers",
    "Senators",
    "Flyers",
    "Penguins",
    "Sharks",
    "Kraken",
    "Blues",
    "Lightning",
    "Leafs",
    "Utah",
    "Canucks",
    "Knights",
    "Capitals",
    "Jets"
]
